name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: biomejs/setup-biome@v2
        with:
          version: "2.3.0"
      - name: Run Biome
        run: biome ci .

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          
      - name: CI
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          
      - name: CI
        run: npm ci

      - name: Test
        run: npm run test:run

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          
      - name: CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          test -f dist/index.html || { echo "Missing dist/index.html"; exit 1; }
          test -d dist/assets || { echo "Missing dist/assets directory"; exit 1; }
          echo "Build verification passed!"
